-- Drop existing tables and trigger
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER LogTransaction'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AuditLog CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Transactions CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Create Transactions table
CREATE TABLE Transactions (
    TransID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    AccountID NUMBER,
    Amount NUMBER,
    Type VARCHAR2(10),
    TransDate DATE DEFAULT SYSDATE
);

-- Create AuditLog table
CREATE TABLE AuditLog (
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransID NUMBER,
    Action VARCHAR2(50),
    LogTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create trigger
CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog(TransID, Action)
    VALUES (:NEW.TransID, 'Transaction inserted');
END;
/

-- Insert a transaction
INSERT INTO Transactions (AccountID, Amount, Type) VALUES (1, 2000, 'Deposit');
COMMIT;

-- Show results
SELECT * FROM Transactions;
SELECT * FROM AuditLog;
